language: go

go:
  - '1.15'

services:
  - docker

env:
  - GO111MODULE=on

install:
  - go build

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic . ./datasrc/... ./infos/... ./render/...

after_success:
  - bash <(curl -s https://codecov.io/bash)

