// Code generated by "esc -o templates.go templates"; DO NOT EDIT.

package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	return nil, nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/templates/default/group.tmpl": {
		local:   "templates/default/group.tmpl",
		size:    821,
		modtime: 1529740304,
		compressed: `
H4sIAAAAAAAC/3RSTWvcMBC961e83UOQycZOr023kEIOhVJCU9JDyEG15XSw9cFYZr1s/N+LLHs/DrkY
S/PmvXlv5FXZqDeNwwH5Y/r/qYzGOApBxjsOkAJY1yasRSZE3dsSb+x6/20vOy7x1FKpeYNOt7oMjhER
kmzQXKtSH8YMv9XfVv9yuz8U/j0yGcX7DQJ3x96Jbzl2GQ5CAFRHTG6HH9rKDKstbvH+DjmDV1tYanF1
NXdfACMFAHhlqZS1CfkDs+Narh8Gr8sAbXzYo4uC3TrLBDBGTc9kOnzewqhGS6P8y5mRV7IhQ1Fg9vCs
2l7j5ivIVnqAm+Yt0jQCqB2DItftHQhf0HG5zHgHur5OLgEK2kRYqn8P2kjKpkrg6X4OVkZgKkyfosBT
Qx62b1uw23V5oquxCpw/q5YqueQAlM4Gsr2ejmNS9pE+cH7uRyYFqoYNXBMBUyYv/vXI7poja1HgHlbv
LiOpXW+rfIakHd57r20lA2fzNdW4XORCidM+56alZVxaqwHbi7dxg09zbRkW2wg7N/uh4FEuPT9J1ZCd
xE+hTzyjEKMQ/wMAAP//OTdi4jUDAAA=
`,
	},

	"/templates/default/headnote": {
		local:   "templates/default/headnote",
		size:    103,
		modtime: 1529743910,
		compressed: `
H4sIAAAAAAAC/0TKsRHCMAwF0J4pfgcUWD01I7CAQ4QlzpEJki6X7SnTPyI8RR1v7Qx11IyBxsa/Gjxj
2uFr327L7mvHRSK+fidqGpJTeY2FJKu1T9rGRge9FuAx7BzgWaOc/gEAAP//80UxpWcAAAA=
`,
	},

	"/templates/default/intf.tmpl": {
		local:   "templates/default/intf.tmpl",
		size:    2160,
		modtime: 1529740304,
		compressed: `
H4sIAAAAAAAC/6SUwW7kNgyG734KIpe1g6mnr1AselggXaTZdntY9KCx6bGwsuiIdGcGQd69oCR77CQL
tMjNlsiPP39KGk3z3RwRnp6gvk/fn82A8PxcFHYYKQiUBcBNQ17wLDf63RoxB8O450d3U1RFsd/Dr2ds
MIBlkB6hoWEgD9YLhs40CEKAZ2wmQTDwOGG4wMlKT5NAQJmCt/4Ixl8g0Kku5DLiQlwYTwXExY9JStnI
GbKsOq/tMpslWH/cgQlHhrquF8jTcwUlP7r6AXlysgMMgUJVPMcmftfk/9fFVX2gU8lVFr+QNurj6rvl
30b9dOJFfSY/0Om98JmdDflIbhr8l8Z4jwECjgEZvTAYaMg5bMSSB+r0bxq82mYEGuPhgMAxrVUPCLpA
A5jVeLforU/7PfjzfUDdBTOO6FsG49y1DEGLLNBRSGWsP9YFXLPKuH377e91d8WCJpbIHiYWldoY57AF
0wlegbEKAdOAgGcJBsZADTLztVoGlVUaRbbtD3Nw+ECnrWOiqx945cESt21/Y00WHUN/QzH5xKUTOiMH
3bC+ozAYHYmqWzLKCm6Xn4z7apxtr6gwIdgOpLesh9/AP3E/4lUvlFgfa/Ak8PnPu7tK+RFRVnAgcpma
hH81bsKNTPuT9Hl2Sp6wXrqMwaVVBypYDWtDvKe48yPmB4YxRVy5OeVN8nZIf1np74MdTLzNy7y0a+qy
BfpWwZiDvuPlxfzWiO0o54jcTg567dCKnRyKtXUc8bSkI9DPOdjmIMv6SI0mRJWHnMuasC5Vbg1I/X9x
tnlxqefLFmms+7nRHPvGLb1Dv2nEoT9Kn9QvDEiBScZyCz8JDq9HanV1kw4WuKfJtXpTdRLWw7efdzOz
2gFJj+FkWZ/l0XjbwMk6p+HBWMY2KdB6Pz5p/vxL7F1diBqE1ho+dWnVMnjrdrrlNRSHUS5p6yoyuTjX
Tdwypa+fo/UcePtWxKpqQ9rdjIH/yxz8NBwwrAlvD2E5BS/GsM5K37N16e+Va/MrPVuyBmQHtON/AwAA
//8hEmzZcAgAAA==
`,
	},

	"/templates/default/manifest.json": {
		local:   "templates/default/manifest.json",
		size:    258,
		modtime: 1529741733,
		compressed: `
H4sIAAAAAAAC/2yNSwoCMRBE9zlF0ethDjBXEQlxbH9MPphyITJ3l7TgJ7ireq+SfjhA6hyS572oj6HI
1IHxUnOSoQ1PGvYpU9vmnc0wlkUmtO9aC7vFRhZGk8NLVUbaCUb+COUsEzZWADknHr49IFEZOnS85lvp
GLXyz0v/4Ya3Dljd6p4BAAD//wb8EYkCAQAA
`,
	},

	"/templates/default/meta.tmpl": {
		local:   "templates/default/meta.tmpl",
		size:    10122,
		modtime: 1529627266,
		compressed: `
H4sIAAAAAAAC/+xabW/byBH+rl8xIRCfeKXp5locChW6gy/RoS58ts+WE6BBEK3JpbUwtcvsLi27Pv/3
YvaFXFKUbF9aFAWaDzHFHc77PDNDqSLZDbmm8PAA6Zm9PiErCo+PoxFbVUJqGI8AokxwTe90hNfFyv5V
WjJ+rcy1ZisajfDqWlQ31ynjB7eiJJqVVNNsecDrskxvv4+epDjIBL+lUkejeDQ6OIA5uSrpL1QTQBUI
4wpW+InxQsgV0UxwEAUQyIkmV0RR0PhEOtL3FQ2eVlrWmYaHEcDBAfxEFMtCHukI7IPGegBr2wggE2W9
4nhXwcdP9jZysPehEgr2f/CfOFnRkZVwWmnGSdmXUUm2IvL+raFXZwKZMq7NIyXl443zGKZT+COwAvTS
2QZLooALzwtu6P0IgNRaHPHMPomMwfA1nDfOplPYfzPIFEmB8UzSFeXaGTYCPH5HC1KXhif++/jpSojS
K96eG43xVuC6OAEta+olOndZkRpOLo+PQVF5SyUollPILSfnyjNJISNlVpdE075Ds9aTK1J9tAEyLm2D
hGEJolQJ5TkLpbezZurMebgxtvm3kQED5jEFFZEa07MbqibIPHeJ1mEcLVj+ZjH9EQ5P3sGC5d/hdZqm
WDyKljTTv9ZU3g8+ejE7nr2dwyIT5SLBh1L4+fz0F1jc3d0tkEFOsd5+unemdTghg3ez49l8FjwEH/42
O5+hHl4lo8pjtzox3YUxuVY0B8Yhk5Ro5NrQ9GvSPVPUPBt/29y1ZX9aaVcDH5he+sxTVKvAw3hNNCzJ
Ld2ZRwkmdFnnjF9PkDnsw+Hl/PTz0cnb89kvs5O5u3ly+mEcu+tTvaSy5ZoJrjTh2rNU6Qj1HtYzzHz0
lnVvvGE5gpGkupbOCQbYAk8YAoBCSPicBEgEkylIwq9pB50sMWBCJiBukAgZpm2FfGzJPzliVsArcdM8
C1ARzrJxsdLpTEohi3Fk9IHFa7XwGBGUVW4OosSKahA01DaOHfNH99eQtnjxsRLqE0xNBY083aNLsNNK
n3Ugsc2BoKZ8PrRB6T70/4A8HZDNzjQFUlWU5+Ph8wQNi4cidhi2mzZgg62lDVnnqSBi8JXReoH7e87/
j7neOt6QbbZm059af57QdTADIahSBQQ4XYfIapwYko7bacb6LxkcZRIQlTY10fNuHHjSOMR4dzKFvea2
dVMjZ9I0otZ0QxHI9TTBLUuzkV0T4Ky0Z30XTQD239ijFkUa6StyQ8e2XScbY0icYJM7LEsoSKlooJ6V
GfLojhOxFdjMBK21LxT46GaP/f393mSzv78/suDCngsuOxIapsB64g6rqrzHgDPBVSDus8mCVo5JCStA
VNrUVdzXvDs5WV6sMPYPw4UbZC1bV7ZIGTBunNvqhdNVo9cWnApc0XDoNRUvIZi8zOzIc8PeV8PD4++R
bNk0aGk+JoCwcVFJxnUxjhAYpj96aAjiaPSMrXf7QMxzmLriVenfBeOedWTGsCh2RgUzoR2It9o0lFR9
jRqjyo5N5ZBJ0Qa2NVaEg+q0+6SbUV8rN2VaRj1DUV6UQBT34dRbPTjIghc/eNrTozPqIqTbSfe1GoDw
fmSMFmEWhwOxcbA9VMGGhT3CIfVmr2oeHMd+HH/oimjVcbIYV1Tq+bm7ULDQcoFbn3A7sL2xqpWGKwq3
pGR5Cud1SZUdg2EfjoruMsbhn1QKpK1pgrpz0EumPNGalSXyshJpnno+OC6vmeqvQLmgin/TH9GbsfxJ
1keFtQGVGxwfrIqNJwwTUioBdZWblU47j3uScabvwL3NSN/avwlQmN3RjEpcU20ozsU6BoptHx5GQfvT
su2U49iC3ist0/fo3XHcxbdwdDgyCkxAijWuSYybeEQNsA7WbbXcvEfktbvJuKayIBl9eHzwCPd2KYQK
FiThLE87reXJ8r8lpbPWwt17TIgxi/2YxNQ/qBTjW1LGsLe3MdKzT80QdXAAFzes8vEymWX3NqaCZAPC
8+aFAK/L0mdJOvIjA9eMByvCMEZlorRKouuas2qJcPJjZI+MB5sz/JSgEmGPe4v7nnlj9AWhA5UwF+iU
KGp7HQrtdLYvQ0hzdHIxO5/D0cn81CLNOIb3h8eXswsYx9EmwgE8Ai0VfRlP/L/l+1rFAzg2hLKLBBaI
s50z6zEE4NAtv3pnSKpMBVMp0SU0xfpx5YQlllilE+PrNE1dpSD5qymOdt1CoVIGUo6KHQWPedIizDfK
pY9LptTKGR6tf8Aw7e355O0l9+Azsa/okihtS/gob8y2XkiPg7NxUyIbtvas9VnsSCdTcK8+EZbw76FS
7Jq3ap4JU/BbFE06KsZ/fab8x6CRcVb6Pmbhc37uLlxv0QIWnK7nps24rnZ1D0yrcBu3fefAU3b7DzLv
tqBTXt4PvNDJWVFQiYE3AVZNg7Aa5Q7XvaJP43oCRqEG3j8wvXTjQQfpDYjS7Cbo3FKs1TfWAKZN/u9q
B+YMPY/iwuPtzeHSWDEBLQ+skt5pKBmE7akKxwqjUORHrV7z+e03eGWlPtmOvEQp1mMVA1NjImm82ZaI
ul7pr29CNkwvaEK+NHpj/UBj8Znn3ycMtounmxqn6/f23HpwuO8hi+nUE/dVYQVw0WRuRncp4xzbtiHz
edvegG1te/Oy6piZ1IfgROglDpEd37umhQ8NrWNY/89rgR0lL8/eHc5ntgldzMxgv2OS7nQZb3Q46fen
bNyfjbFNpA0goD7WCS43TKjUeM+6RMu437M+v6xdBWDpQNEuFfNzd9EM3E8gYR8BDW55Xi+YR18GWLYz
PguwnjW/vjMKb59f7Rc1FZHUOnEHSPxbA7d13dsWTBtLu5/Oz92Fi2UhxeqF0XRbSimymwU6Rstmc/Kb
rvkW5vQcbKFEbSdTfs3RzbrIhQstK4B4Z6s6y6hSRV2W91CImudmDLLPNK3QmzScUl+sP7fnVAJoA1wJ
Ubbp1XjOM8eydBVjmyo+lEAUxT3H2m+3tjs3q5UWK/PyhJlv3P5HvOsd8HUeTozhzatZUylpmgZ18l8o
8Qtj4infXeXmlQHP8ZiuKn2foKeDLuzjaQUb0ikuTU5upwe9anvQDo2s0yddsXBVa+s3ZpbGKO5shubl
Wb+f2Aa6G3t+RwMcaHjB6y8bahcHkwDhVveHKURh+g7Aqdsymq1rGFK1TPndmaQXGeHjPUu5gaQY1skU
vqTmzrlYP29lw0FNrFPD2mmTpkMrxuY65+5Y7YTShkdsOqopq6Fo5FRp+LZj4vZG+LAr81/8LvdbI7sZ
r8zHpD8xVrgX+q9o7Nul5nUIdErY/GjAVLBaM50t4Rb1uCVlOtb3FbXaZ0RRKEpB9J++m4RuvDUzWofi
+z/voEBpm8f+iwdDwrj+yw4OjOs33+8+36kj47s1rJ+QXz+lQP2UBvVTKmi2oumcrWiXJj2yIYw9nYXm
TUbm7Y+hML9Y+nkgbq9uLdZuEvY0GyT8qR/FQaqjviO3UfXcuY3sOSYc8WcZcMmepdsle55yl+x52l2y
56m3EftBqovN8Ad07t2kPd78mtjCwQSXMFB1ZX5GpxFYEI/Mj2BezyP7ztE1nMfRvwIAAP//EON6j4on
AAA=
`,
	},

	"/templates/default/meta_test.tmpl": {
		local:   "templates/default/meta_test.tmpl",
		size:    6246,
		modtime: 1529627530,
		compressed: `
H4sIAAAAAAAC/8xYX2/iuhJ/Tj7FbB5WySobGlqhVaUKsSW9t1KX9lK6K93N6mCCoVGdmHWc/jmI735k
OymBGCjbHqkvwYxnJjPz+3lsZ4aiOzTFMJ+Dd6XGPZRgWCxMM05mlHGwTcOKaMrxI7dMw+I443E6lcM4
wZZpGtY05rf5yIto0sg4wzy6ZQ2pN3lqoCzDTFpO6exu6sVpo9sZdD53L//TmNLP2W+S0OjOu/dXVO4p
QTwmmOPotpHmhHj3Lct0THOSpxEMcMYHaETwN8yRzeFTEZQ3cGBumoZ6JxyfgBp5Pfxgc8c0jblpGAnm
SMzZnwYZ9x07jYnjLd05plE48ILfOSK2xTPuWy4IO48LPVGimtrPXxlncTqdW5HQtmZN+ZRj5FuLwkFE
SZ6kwkOmcRGnfN50wS+1ZyxOEHs6lUbZFa3bHBaaKOf0PI2Upk7x568RpWQ+QSTDLhQ/nOXFs3zjLcq6
eIJywmseEjT7qXKUcYo8j+FApXoMvsr2GJoq4WM4XM052x3VMpwiwtJDnF2pStTRGc784UkbOr0uDGfN
4UnbWq9dOq5bXQcXwekAhpE/dKWdeMox8odw1r/8BkOB+7D0lmGCI/6/HOti6AYXwSComsGP/wb9ADYG
N8aC3F+firRKvwsdR5sv42hzf45GzR28vMCprSeiCwc195/9V5DxNQSMJAH3pttLKfYiRr2IKDvhX1Ra
3HkqTAf9PTqcMR65IBqqC5gxMV82WKHgmEY8kRMfTiCNCQiqce8McURszJiMwBjjCWYwHnmnhGbYFm2z
0YAOIfA3ZhTuEclx5hU8Fa6DxxmOePCII9s6710H/QGc9waX5UoIQ3u5zMLQge+di5vgWsjDsO1CGLbD
0LEczzQM40fMbztsmslSHZQyQvqY5yzt4ywn3K7kVEj8Qxd8R9Sby6xFZ58vluXv0YAxyuy4LGmxo3lf
UXQ3ZTRPx7bjgqjeR84cp25ZyRTxmKbZD8zEYrSdGsry5ZF/DCKHWVNSdObLH+Qfgy/6ImfFam80IHic
kTjiIFYNxGnEcIJTrgr9p3WutjN9zZePDdUX+5ALh6/DQNiK3H1XjppiexAjUYhDMXo3IDUVSL4CqYJR
dUnezMaI43eyJHsUilYHnEIuQyv4srYKUvwwkBLO6kXLy5y2ltuFj9KLs+TtZYqLALa9fxX3Zy7Uw5L/
vMiHE7DQKLJ0tL+56nYGQcn460Dt4Cdh2K5uuOLv85Ybhu0au4V7ye7mi9l9UJL71dXbh7Sy1lUCduXG
8R4I+HKYayhuPy7tQu9NYBuXdXzTHrPeLq7fDVqNBshDBoyeoDjGeH+IofSzxwn61djSh2wFWfF/123L
8TrjcZ8+2Gq+3Ms0eKrz2u4FLA+L2/YR+aKtO4kWBniI+S0Qkdw7AATOLvuguuw7wkacuHfho26NlvWW
EEV5xmkCEU3HsVjr+t31DaCIqlAgf/hBu23J8A//PQyOXotBca+yZD7VbNrytqnC3x+fowo+Kxek7P+Y
0b0+AE0og79cEPqnKMNChaF0ikEWLI+47KjfEQEAiFOO2QRFWMKs3gbiAmkaC6E2nxCK+GHTPnDKjyhV
qe88XzGfxa0jnXLrqKa8/CCiBCsfRYQgTvmXNV9StOYoTrnfquv5LY1iLRMlqyvWslCyNcVcE2KuizHX
BZlro8x1YebaOHNdoLk2Uh4n2BvECZ4vVmouxD36YK9qixvDUskSnK3Myq+VZ4oCq+6qM2eMJutRLOdb
R5ssW0cbLb9SSjRmQixt1AZWtztP+ReNnRBvfNe5wEZv5Le2WWlrIuXbrLT1kPKNVjexPi0p32qlTUxN
bLXTpqYmttppk1MTG+3qXH0WS5slczXG12pnqJurCenAsqqGC9kVV5p22UE91RZdiItmXMq/I+IU9+d/
AgAA//9wgb16ZhgAAA==
`,
	},

	"/templates/default/scan_type_map.json": {
		local:   "templates/default/scan_type_map.json",
		size:    622,
		modtime: 1528164482,
		compressed: `
H4sIAAAAAAAC/3zRv2rDMBDH8d1PITQbg1sjiscOBc9NJpEhgSRcUE4QS1PIuwf9udNl8fi1P/yG07NT
Sl+cP4bvLz0rpSxXrzRG54a/2oeerZmkNdOnNVO1J+9dhtnmIviboijA8NNULlJLiqKiYLYWsT00BxhG
w66UmBuN2CNoqeQgS0C6TV0Ut1mwXSYKaKnkIktAumBdFBdcsN0vCmip5CLLAPdzu2GqYZc+Ec5RHwUC
SWX1Gh6AV3b/JYu8rR7b6Jas/+ZN2b26dwAAAP//G8mEhG4CAAA=
`,
	},

	"/templates/default/stmt.tmpl": {
		local:   "templates/default/stmt.tmpl",
		size:    8521,
		modtime: 1529831271,
		compressed: `
H4sIAAAAAAAC/+xZW2/juBV+1684FWYDyVWlbB/6kMIFZtK0G2CbySaZ3Yc0GNAS5XAjUQpJxQ4M//fi
kJRM3XLZDrAP7YstkTy373yHN9UkfSBrCrsdxJfm+YKUFPZ7z2NlXQkFgQfg56Xy8T+tuKJb84wPiaJl
XRBFdUtGFFkRSRP5WOiG1bOi0gxmJfU9fFozdd+s4rQqk1/LiomK4/AtjuJNUYC/ruqHdcx48lQVRLGC
KpreJ9gXP/3F90LPeyJCu5UkcN3UtaBSgm/cpRkQngGvFDSSZj5QISohYw/gKywhL1V8KRhXuW2wAcWf
SPqwFlXDM9vRBhafyxvRUNsqH4v4c0354XUbI2CtlPbygm4+VVVhmzQGuq3Jcypa9ayk8UW1wXB2OxCE
ryl8kKpUcLKE+FqVSuosAObmA8eknCzNCN3bpsn0N/0BX/q96rkeSN9gS9dPxFpi/9lWCZKqj2Itz3le
mfHdqCci3FE/EzE1apO6g35hRZYSkfVH2qF5QdbXjK8L2g7TTm5SGQ+aO+0o8gOR7vi1gqCg3Mh19kI4
7kt9kfTGplRbwWjiH4gEv5H0a0fjvtA5/6mh4nkgwPjXR2weDL6iqhH8M9f66SMERuRnUjQUfKF7/RD8
ihszRpTlONakyL8++/Hs9MY3nUazoLIpTLZPlnBDBSfieRK74EtdU3FKSlpAwHhGtwNM4DiMb8iqoOYX
dYYQ1LocwP9OXmlTvmVTCI4bLNclNWUWRyXJ0Nf9HpgEdU/BNEKVO0Td72NPRzyWkko0qYKdtqxt29pg
EXxIq+LAY50a4/NpVUj4k85GJ/Zhk3Z06kb9uXP7A5sQOLX6p2WwdyzGciuJmWZZr9vNsBlzWUk4tmOM
za5YYdE5YdPklLGjj/Js6AMtJD0odXiAiMWt/t0OrlPCde1rKAdKenqdhlEqHGQP5DKifHvRFMUwsl7r
ZGyOOdcgy/V0HnTk64osHE8Gc0y8LlhKkY5SP1gm9obM0dGI3t4tRj3aFN9OS8iXrekx1uS8itu76R6v
D5lObLJ4P1iLBKPIG55CYIt0HGYIfHspKPImyKhUsLi9Y1xRkZOU7vbh/0ShGkTiSW7HfXzC99TqQiO6
BFLXlGeBfo3gyJqbr+TwTWX7xuRWUmnvQ7NVmkjoC+WOkAmB3a9h1Jn5q5b4wxI4K6wxszZiuwfgAD6c
Rl6x8llkDFfHIBxWiNfZ4Kz47yYYA6mp7cV0gSKsP1JElHGzklnjBeXBQouG3ttVnStaBgx1aYVt6bmK
W6237O4dij8a2jFFSxjVdLX6FdMaTLAm4KwITfK1bC+XKLfU7fGUrE2w8dehvn6PUFpDkySAGykTngQC
Um86JiZuOFdQE85Sif7ghqOgfK3uceKV7cSP2f0+fhsunzkNwoluHR/L3SRi5N/buLUPAZ4vzrCM8sCf
mfYxrnsi4bsMRLWRfuRqDMOuAvqJPcbEAriF/1J17vfdhGfX20vBSiKe7dy33yPEf2dSMZ6qYZ21sGe2
H4LVM9RGATzhfjYcbV4Y1+BLs7S9CekZ80HYLrijzQJCrcwpZLJfK94hUHiWqz89B5ZX6M8E0bX0VbX5
hal7C1B/Sprl8XBuwrRFcKSEjMCWh1WhhLSM/qfxaYicdlXC6nmEKc5MvyUXG6bu0aC6p0wAkbJKGcGj
sWxWxlxXHfKNuZr2PQghmMtVNLuBMRPMO/KoB85ulH73fB8ZJ/s5j6zr3miPrWvTrksu+BIWszG+YUmR
wzXlNX36SbQri3lzVR8FneZbdvde7XZxMbm2eobzfVsr+2+7pZ3TNH+C1XLGBS9ZeO5BFZePVFBdPrmo
yhN7br+idUFS6typXIsU/H9zH38A9BF/kRjIXIVBqrbdtdOp+Y/gEfQumYrDxE7EWs/sRKxl/FGspS4q
e1+DDc65rm2y9zpd9CEEdiHo31Ds92OOt3tT/TSR1k5pZHaKJrVJAhefb85O4GOWAQFOJSK1Kqr0AVQF
pCiqDbCMcsVyRgXIe5JVG8bXMeKoQU8S+NSwIgN9qxLrNv0YAcYetVtMvtXDXDA1aEFJ6lupBONr92wy
3siOET1snP0xsP7JBNqRN7nztntyux/u7YjcvWdkN7m4yPc2oaP8tMj8dMBEVBt0/9EeqKqNZQ8yKnIR
i+M49FoF/2BFATIlHOpKoyONtvYNVZbkgQa9g10Ex4Zrmt4XTdk/xHWHEHu2OFnC0ZhQe2eIc046ak0f
nMR24xbCt8RQYz228xlDmkfYti7NDe2ZEBfVVbWRXX8/B3gIMK371zOUJICHFwuhqFIqLYITh58Xjzlz
Zpweo8h46PWPjL2pbFzOyRxlDvVjifMia95LYvzNaE6FNhWfFpWkwVReTWSabVPXKZYr34aUeWXducA4
D3cUL1SDY3rZPd4enxzfdeG/SvQ3UH0AikN3OcP3uXRMJ8SZV+Z5+1uYO2/OjdxZ4W1DZHvCOa7LEdmH
y/Y01/U5yWtv0ccVMnGpbuR+n/WdwtmWpt9+eT/c2fx/IX7zQjye4TE5jaIm5K+RLUsaY/ur8+Xg+qrj
5JDIs5Rsv2c6fHc/V7U36yO8b8q6cD9V/quRKujeLujGXEK0Mn4YXxIhKW4Ju68+f3z0Lcdv6FYhp0Jv
eE85YRr0yW1ei9dLTGiPDrPEyYgiMM2eEALTiAfK3mLg7EJnkNN+JAkcoPwboF2H4asmRyqar7TmE+2u
f7M5A3xsORMcrZo8AozghbtN34/cqVOjio503xdXTR5f6ziDsDen2dLue92XnfDQpaA3UoE4dLqmKvzw
YTs4mLJBetPVNRdoPzvtF9U2rrNtjQc8n3HfFNWUQ9afcx6My+89rgwwscN65uz9sDeq37kv9KaCvf8E
AAD//xLXhidJIQAA
`,
	},

	"/templates/default/table.tmpl": {
		local:   "templates/default/table.tmpl",
		size:    8382,
		modtime: 1529675232,
		compressed: `
H4sIAAAAAAAC/7xZXW/bOtK+96+YGj2tFCgK3ot3L7IwFm3axQabTbNtcvaiKDaMNLLZSKRK0nEMw/99
MSQlU5b8kaLn3CQWRc7MM98c1Sx7ZFOE1QrSG/f7mlUI6/VoNOJVLZWBaAQwzqQw+GzG9Luo3H/DKxyP
6NdU1o/TlIuzJ1kyw0s0mM3OxLws06e/jEfxaHR2Bl/mda1QaxDSwFxjDqiUVDodPTFlufwXJuAZpe9Z
9jhVci5y/6KoTHqjuDCFXyD26bVc+EfL7RoX76UsieNqBa8FYTmfQHrLHkp0fxt89H6+teGuBX92BpsN
6zUoJNlRGA0MlFyALMDQGbhvGa3X9+nILGvsHtVGzTMDqxHQumJiivA6k2XA90KW80poOF2v3S5630pD
C18yJm6JtD25XsP9dy3F+bjZ6yj4A2PIH3a9uncMUOSW29oqiheNJDeKV0wt099Zyd2OszMQzyEgv+V3
Vs4RuAYzQ6jdGjzZRVl0NOCVsofKESpqBHu5qrYB+wdvZfF8PS/LjsG4ts5krfuESnMpepDg0rzVUDEu
yqVz5kIq0BkTgoup9ZDFjGczqNjyAeH67uoKIkynKXABcm5QwXfJRdzqpidFoBOpci5IveGGYP3GKDjZ
eneEqznDUzRaHV43mJ1qhRdoW720ba+Ku961FUhfSp5Zr9H2x7Cn9A98/dbF5yx3o5AkAVbXKHINrCwh
8/iMhBy16ZglhcuqLrGyYewUQecFKuDCoCpYhumomIsMom2Vxht+kSV88vVbe2i1jq2hTuybiRcoso/J
0XEPYFS6rfKk674A8aiFL7Wx+HNJVpz9CoSeZBS75AwrGAEoNHMlQPASiHmTrrsB/S80DCZwjQuLjR4j
C2ocJMhxYpe+ftNGcTFdwWp1ul816/WORJYEaoG1o/upNv7cf7iZfcCCzUsTHdJ+EwmWyT+Y9udcajrM
v/X49Tp2YhzIqF5S/8JLER2b+I4RaCPHxm+2xHo3N/JSZI5EX7jO64g4Dp7rSjDENvbVv3UK702ubrgS
WtEyF4VUFTM+2w4V19C5Lb3PcnGMX28cMoaTjSCrwLV7ruyjzCmmFVlRySvAzLimJMao4PHcC0tJ3+V4
yqmU8uOfFtnyjWJ4kLIMBTUKXk0oEr18zgDOVUPF8lMz87lwU5R/pU4DxhGnAzEE6dCKrBfcZDPgW3Wd
J/vTYMa0KwEc1utz61Et+F563M6OuYtdd6xmgmcRNY4fKZkV1o83xSaAcA6/5VSWSUtWzHECPI5HAOuO
om+kBblL1W811H7HH6Juz/5PU/ibP0TjHsUBnR9uSzstZGiRpht9xKAjtTGr5GLQBFQuPLljrBFyjvp2
oAyhYGLj1C6EJdTi25F4QrqrJpe+oB3uN8Tnu3qKLSsGjfGp768uhUZlKM3Z/tZI4G6l0SThls7LUzpw
/en24znc0tsKzUzmkEt0171K5rxYusudMNQD3xt1D/icYW2AzS3xTFmrNGkr4gXgM9dGx+kR3nCnET5j
KZkVdYrGuoLABbVkOTMMCiUr++uBaUxDuLvs7FQQZea5vZdeuP8JIHx8xgxV2yltjOr0dPuZDiaACRgV
H+fSHkCgc+UhNTq3ILzOd4ntqAyL/QP+PUe1HJRbY4lZK/cPkjuBgpUa4+696VggFFZXMnvcB2jBzQxK
2nQ8tIbuL4JIZf3FCO/qnBkMkc3dShAeHg18olticzOxgHNeFKjI222CotWyhAf0RPKfC6ize4GLW3Wf
wk9FxC6lO6j7wyABy3r7aM8ADl8nNvzRF1vgA5bYtUDuVl4ULI7Ki2PcserFeHe4cCHr5abw7Cnu9ZJa
08793/OinP8mfLGidH1CbyZwYtRGIoXGJxlfMYrHoGD8/Z/hzERhYZdpw+viMf3cPHe2XIocn4Mtd4L/
mKNbbTfSxanZ27VPyKitPe+XtFw8bmYKYeVmWsuMUwAMn7ZWfVi6piogck/3fORTQTU/8aEW6fi8Vz/p
1OYq5Qj17lL3rRl3G+04dAcyVOIyH3X5MUQngzQT53zx8HgsxNO96A0NdXgBrwYaAm+37VYlafoVCEZt
V40pzidDvQUtuJlN1JsUxfD/sBERS41bY7wDtPttSxBureB7DNP6aWieBH4c8JKkJ2DL1xmQIr8jWdhK
BY14E08+Ji9FzjPU3Viym9JL7YItjKXG9xwW3gESZkFX47oXj07geBb0t40ft+a8/RCzA07d16Y7vk+h
drIozdBwcUvXnWBppGxihDzYKOLZS5nUTSr7qukBLqTI2z7gjfHBmMD4/w4jgHfXH3Ylj8nfWpHHTat9
up/gdvt+tdWpn4YTlb9aIK+GrxdWE907hoXmRgZDTvqnjVP7Q+5fNFQ9dMHdnQ/BXnGbOfrO4esmU7kD
Q7Px3qD20NS2mmtDHV/GyhJzYIXB4AsCKVyClhUCPhvFoFYyQ631r1N8b9ZLSfSJKTv6v5AluCHt6CUf
rvZ8UPC1Z0h3nfrTcJ/AjkGn3TWVRsLFDLPH67urK+/w+2wJtqQMcj9csvbY1iGztyQPoO3cL6taas1J
BQ+KiWxms3PzGXRcsgcsNxggx4IL8gSRt99Ix8426S7MI8vuHUUqrWuomdaYd3VxYxRMOp7eGeqPRi3N
c4fmxI0vor7jNEHpUM7LkgpLAhoN1EYRPsHLtPmY0RXANRO7ZyHbY6NmavSbhoyJtzZYSMhx0viIjSoK
q0/NF7KwmRz8bJbCpdkOPUnXMxd/m7A4FEANy12Nux9YBiogYR1N9/HrpPedi8LyCoUbKYWEShTRiT0V
H0fl0mC1a0zoaTYEv/Jvx9F85xIwN1hBL0vLh++UF7plOY4EL2PnU/ZYp2jRkYldT7eOeb9wAgap3z4n
dNCq4X8BAAD//52VFnS+IAAA
`,
	},

	"/templates/default/test.tmpl": {
		local:   "templates/default/test.tmpl",
		size:    2130,
		modtime: 1529627540,
		compressed: `
H4sIAAAAAAAC/7RU32/TMBB+jv+KIxKVXZWO3N4m9QEBDzwwKpjGwzQhz3U2a6ljORfKVOV/R3YSmm3p
BGPdw+qzv/vx3d0XJ9WtvNaw3cJ82Z5P5VpD0zBm1q70BJwlab6mlAnGjo7grKIMTAWkK4IzeVXor+UG
NoZugDblG1UW9dqC82Yt/R3c6rs5ozunW7+KfK0ItixR0TD2miUOwVg6Rpa4rD/J/tT0SXE8aVnTeDIc
T6ZwFzhCqaJs2QY4l0WtB267ctzA66f0oSc/dnUM/hbAp4Gp4NYUYoj6buimy/MEaiQWdijBWF5bBZw8
tN5gfy29/qak5avQmOnFpbGkfS6V3jYiUJjGhwVI57Rd8WjOYEJ+rrL212H329kyE4HlSKqyophLgPa+
9CG811R7C9YUg86Ejn7WJGEBp3oTmQWTsyRJw1s6Y0lycdlOZJuqLJ1B6jD+j2eZpU3AfHHUdex93KqK
dwCHqegA3Uvo7gedy7ogvovSg97VVH6yqsXy/mW0pbtyBUz/GAOuPbuxJp3Lwqy4gKuyLIYuHl4t+iY9
9GmLiqvHTdgyAYMhhijVxpC6ARM3WVYa3p6wZBd7rrLuPrt/77C7xwf3Pf74/r3MWLJqexgenLRG8XxN
849h3DlPX6+CBoPiyhy8tNc6nYERgiXNfmbLMtJ5DrfJPnKTfewm++hNDsBv+NXgj5iZPMx9Eece7KFW
kubeOg0DBaTLTto5hfV12Bo4GysDX+YjoFDsCf0PoscnRI+jolcYhf5YiPh3QsRRIeIzhIiHFKLCF1w8
PLSw/rPa3wEAAP//N0x8k1IIAAA=
`,
	},

	"/": {
		isDir: true,
		local: "",
	},

	"/templates": {
		isDir: true,
		local: "templates",
	},

	"/templates/default": {
		isDir: true,
		local: "templates/default",
	},
}
